services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://postgres.skzvqiiudunulmcjnkbh:Az-2004%21Masha@aws-0-eu-west-1.pooler.supabase.com:6543/postgres"
      TELEGRAM_BOT_TOKEN: "8703406337:AAEmKfdAmA2cbKIv81Pk6MHv6cwir0u3QV8"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
